// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreStudy.Infrastructure;

namespace NetCoreStudy.Infrastructure.Migrations
{
    [DbContext(typeof(StudyDbContext))]
    [Migration("20201223102457_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NetCoreStudy.Domain.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<int>("DataLevel")
                        .HasColumnType("int")
                        .HasMaxLength(11);

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("NetCoreStudy.Domain.Subject", b =>
                {
                    b.OwnsOne("NetCoreStudy.Domain.SubjectDetail", "SubjectDetail", b1 =>
                        {
                            b1.Property<string>("SubjectId")
                                .HasColumnType("varchar(64) CHARACTER SET utf8mb4");

                            b1.Property<int>("GradeLevel")
                                .HasColumnType("int(11)");

                            b1.HasKey("SubjectId");

                            b1.ToTable("SubjectDetail");

                            b1.WithOwner()
                                .HasForeignKey("SubjectId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
