// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreStudy.Infrastructure;

namespace NetCoreStudy.Infrastructure.Migrations
{
    [DbContext(typeof(StudyDbContext))]
    partial class StudyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NetCoreStudy.Domain.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<int>("DataLevel")
                        .HasColumnType("int")
                        .HasMaxLength(11);

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("NetCoreStudy.Domain.SubjectExamination", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ExamTime")
                        .HasColumnType("datetime");

                    b.Property<int>("InvigilatorCount")
                        .HasColumnType("int")
                        .HasMaxLength(11);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PassLine")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ReExamineTimes")
                        .HasColumnType("int")
                        .HasMaxLength(11);

                    b.Property<string>("SubjectId")
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Examination");
                });

            modelBuilder.Entity("NetCoreStudy.Domain.Subject", b =>
                {
                    b.OwnsOne("NetCoreStudy.Domain.SubjectDetail", "SubjectDetail", b1 =>
                        {
                            b1.Property<string>("SubjectId")
                                .HasColumnType("varchar(64) CHARACTER SET utf8mb4");

                            b1.Property<int>("GradeLevel")
                                .HasColumnType("int(11)");

                            b1.HasKey("SubjectId");

                            b1.ToTable("SubjectDetail");

                            b1.WithOwner()
                                .HasForeignKey("SubjectId");
                        });
                });

            modelBuilder.Entity("NetCoreStudy.Domain.SubjectExamination", b =>
                {
                    b.HasOne("NetCoreStudy.Domain.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");
                });
#pragma warning restore 612, 618
        }
    }
}
